### ISSUE TITLE
SwipeRefreshLayout无法触发

### ISSUE THREAD

**Issue by chenwulue** [WuXiaolong/PullLoadMoreRecyclerView#10]
重现步骤如下
1.当前总item长度大于屏幕，且当前屏幕第一个item的position不为0
2.执行删除item操作，删除到总item长度大于屏幕时，当前屏幕第一个item会自动显示position为0的item
3.下拉，无法触发swiperefreshlayout

**Comment by WuXiaolong** [comment]
感谢反馈
