### ISSUE TITLE
加载的时候无法拉动recycleView。。。

### ISSUE THREAD

**Issue by smallgirl** [WuXiaolong/PullLoadMoreRecyclerView#12]
加载的时候无法拉动recycleView,体验很不好

**Comment by WuXiaolong** [comment]
@smallgirl  为了修复这个bug：https://github.com/WuXiaolong/PullLoadMoreRecyclerView/issues/2

**Comment by reancool** [comment]
也是 下拉的时候 正在加载 不能 拖动
