### ISSUE TITLE
列表为空时，下拉没反应（不能触发刷新）

### ISSUE THREAD

**Issue by luffykou** [WuXiaolong/PullLoadMoreRecyclerView#13]
修改文件app/src/main/java/com/wuxiaolong/pullloadmorerecyclerviewsample/FristFragment.java

```
private void getData() {
    new Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
          //mRecyclerViewAdapter.getDataList().addAll(setList());
            mRecyclerViewAdapter.notifyDataSetChanged();
            mPullLoadMoreRecyclerView.setPullLoadMoreCompleted();
        }
    }, 3000);
}
```

**注意，注意，注意！只注释掉这行代码
//mRecyclerViewAdapter.getDataList().addAll(setList());**

**Comment by lsw8569013** [comment]
mRecyclerViewAdapter.getDataList().addAll（new ArrayList()）;

**Comment by Lizhny** [comment]
这样解决好不好，把空的list替换成提示语

**Comment by lsw8569013** [comment]
提示语 ，如果不放在list 里面。目测会报错~

**Comment by WuXiaolong** [comment]
此bug已解决，多谢@luffykou 的pull requests，增加firstVisibleItem == RecyclerView.NO_POSITION判断
