### ISSUE TITLE
这个好像不是给RecyclerView添加Footer吧，而是在RecyclerView所在布局。。。。

### ISSUE THREAD

**Issue by gaolonglong** [WuXiaolong/PullLoadMoreRecyclerView#16]
这个好像不是给RecyclerView添加Footer吧，而是在RecyclerView所在布局下面添加一个浮动的加载布局，然后监听RecyclerView是否滚动到底部，如果是，则显示加载布局，数据加载完毕再隐藏Footer。但是有一个问题就是这个加载布局遮盖了RecyclerView的内容，而且显得突兀........

**Comment by WuXiaolong** [comment]
最后一个item一出现就会触发加载更多的方法，其实最后一个item还没有完成留出来，因此感觉被遮盖了，体验不是很好，算个bug

**Comment by Focfa** [comment]
重写RecyclerView.OnScrollListener的 onScrollStateChanged方法，判断当不是滚动状态时再加载。应该可以解决。

**Comment by WuXiaolong** [comment]
目前版本加了一个动画效果，体验好很多了

**Comment by Creep0824** [comment]
现在还是这个效果，在RecycleView布局之上，达不到作者GIF上的效果

**Comment by langrenfengzi** [comment]
的确是没之前的load more 习惯
