### ISSUE TITLE
不适用于带header的adapter

### ISSUE THREAD

**Issue by langrenfengzi** [WuXiaolong/PullLoadMoreRecyclerView#19]
1.使用那种包装过支持addHeaderView()的RecyclerView.Adapter，这样通过getItemCount() == 0来计算是否有没数据就显示EmptyView就悲剧了，另外带HeaderView时设置emptyView会覆盖到headerView上。
2. 有时候习惯getRecyclerView()后直接操作RecyclerView本身，然后setAdapter()，这样adapter.registerAdapterDataObserver(mEmptyDataObserver)就不会被执行，关闭的时候unregisterAdapterDataObserver()就会导致throw new IllegalStateException("Observer " + observer + " was not registered.")
不知道Observable为何不设计成没register过的就不处理，也没有检测是否存在注册过Observer的方法。

**Comment by WuXiaolong** [comment]
感谢反馈
