### ISSUE TITLE
当item的布局高度大于recyclerview的高度时，无法调用onLoadMore方法

### ISSUE THREAD

**Issue by chenwulue** [WuXiaolong/PullLoadMoreRecyclerView#21]
当item的布局高度大于recyclerview的高度（单个item无法完整地显示在屏幕中）时，无法调用onLoadMore方法
因为findLastCompletelyVisibleItemPosition返回了-1
改为findLastVisibleItemPosition可以

**Comment by WuXiaolong** [comment]
已改
