### ISSUE TITLE
viewHolder.getAdapterPosition();获取值一直为-1

### ISSUE THREAD

**Issue by smarthityou** [WuXiaolong/PullLoadMoreRecyclerView#24]
@Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View v = mInflater.inflate(R.layout.staggered_recycler_view_item, parent, false);
        final ViewHolder viewHolder = new ViewHolder(v);
        viewHolder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                int position = viewHolder.getAdapterPosition();
//获取出来的positon值一直为-1
                Log.i("info", "adapter:onItemClick: " + position);
                if (mClickListener != null) {
                    mClickListener.onItemClick(position, v, viewHolder);
                }
            }
        });

**Comment by WuXiaolong** [comment]
请谷歌recycleview如何取position
