### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by eicky** [WuXiaolong/PullLoadMoreRecyclerView#29]
当下拉滑出进度圈后，然后上滑动回去，此次不触发刷新事件。之后就再也无法下拉刷新了

**Comment by LiuJQ** [comment]
有个严重的BUG，下拉刷新，加载完数据之后，发现界面不响应了（无法滑动也无法下拉）。。。

**Comment by WuXiaolong** [comment]
刷新结束，需要调用setPullLoadMoreCompleted()
