### ISSUE TITLE
上拉加载的问题

### ISSUE THREAD

**Issue by lpslpsl** [WuXiaolong/PullLoadMoreRecyclerView#30]
如果里面的item比较少的时候。占不满一个屏幕的时候触发不了上拉加载更多的说。

**Comment by WuXiaolong** [comment]
确实是这样的，触发不了上拉方法，这样也是合理的，一屏都占不满，就没有必要分页了

**Comment by lpslpsl** [comment]
如果有这种情况呢。就是服务端分页嘛，每页五条数据，这个每个数据的item的高度比较低，屏幕就占不满了呢，

**Comment by WuXiaolong** [comment]
对，但5条10条20条不是你（客户端）说的算吗

**Comment by lpslpsl** [comment]
恩，的确请求的时候可以传一个每页条数的参数，默认5条而已。
