### ISSUE TITLE
ui问题

### ISSUE THREAD

**Issue by piratejason** [WuXiaolong/PullLoadMoreRecyclerView#32]
@WuXiaolong android studio, adapter 的布局是 android:layout_width="match_parent"
              android:layout_height="match_parent"
控件也是  android:layout_width="match_parent"
              android:layout_height="match_parent"
但是在ui显示时 只有半屏左右
怎么个情况
图一是预览
图二是真机
![2016-10-27 15 27 03](https://cloud.githubusercontent.com/assets/1669190/19758271/e6a74fd0-9c59-11e6-9c9c-3a7b9edcf829.png)
![2016-10-27 15 27 27](https://cloud.githubusercontent.com/assets/1669190/19758278/eee6cb30-9c59-11e6-89d5-56c232dda7bd.png)

**Comment by codyer** [comment]
@piratejason 请贴出布局文件
