### ISSUE TITLE
重复解绑造成闪退

### ISSUE THREAD

**Issue by TanShuHeng** [WuXiaolong/PullLoadMoreRecyclerView#33]
异常输出：
java.lang.IllegalStateException: Observer com.wuxiaolong.pullloadmorerecyclerview.PullLoadMoreRecyclerView$EmptyAdapterDataObserver@53ae2ba8 was not registered.

推测异常代码块：
@Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        RecyclerView.Adapter oldAdapter = mRecyclerView.getAdapter();
        if (oldAdapter != null) {
            oldAdapter.unregisterAdapterDataObserver(mEmptyDataObserver);
        }
    }

推测原因：
在Fragment中使用该控件，第一次调用setAdapter方法时会去注册一个观察者，在离开页面时解绑，但如果Fragment没有被销毁是不会再去调用setAdapter方法的，但在异常代码块中会再次调用解绑的方法，造成异常并闪退

**Comment by WuXiaolong** [comment]
请试下最新的1.1.2
