### ISSUE TITLE
滑动监听是哪个呢 我打算在下拉的时候出现渐变效果 但是我怎么也没找到监听

### ISSUE THREAD

**Issue by wangye21323** [WuXiaolong/PullLoadMoreRecyclerView#35]
我的现在需要在第一个item消失的时候出现一个渐变的动画效果, 但是不能在你这个上边找到滑动监听, 找到的setOnScrollChangeListener 这个也根本不起作用 望告知

**Comment by WuXiaolong** [comment]
可以自己加下RecyclerView加载动画，不在这个库的范畴
