### ISSUE TITLE
下拉刷新动画异常

### ISSUE THREAD

**Issue by louisyonge** [WuXiaolong/PullLoadMoreRecyclerView#4]
当按下拉刷新时，在动画开始刷新，但没结束时，此时再下拉刷新，这时，出现bug，那个动画就卡在那里了。
这个问题怎么解决？

**Comment by WuXiaolong** [comment]
@louisyonge 用最新的compile 'com.wuxiaolong.pullloadmorerecyclerview:library:1.0.2'，没有这个问题啊

**Comment by louisyonge** [comment]
@WuXiaolong 用的是这个版本。把主题和依赖改的和demo一样之后，就没出现这个问题了。可能是缺少某些东西。。。不确定
谢谢
