### ISSUE TITLE
RecyclerView: No adapter attached; skipping layout

### ISSUE THREAD

**Issue by wuchangfeng** [WuXiaolong/PullLoadMoreRecyclerView#5]
调试了一下您的代码，发现logcat里面也会提示如下所示。所以感觉我的错误不应该是这里。但是还是想请问一下，这个如下提示有影响吗？
![www](https://cloud.githubusercontent.com/assets/13432620/12437881/bec15b62-bf5c-11e5-853d-20e0edc65d04.jpg)

自己的数据接口调通了，但是在RecyclerView就是现实不出来，提示如标题错误
![bug](https://cloud.githubusercontent.com/assets/13432620/12437414/b021ad5e-bf58-11e5-8403-7f88f93eba4f.jpg)
adapter.java
![adapter1](https://cloud.githubusercontent.com/assets/13432620/12437655/a53818c2-bf5a-11e5-9ddf-d2c18c0ba8ce.jpg)
![adapter2](https://cloud.githubusercontent.com/assets/13432620/12437656/a55841ba-bf5a-11e5-880e-49e77c086451.jpg)

上面是我获取数据的代码，不知道是哪里错了，还请有空帮我看看，谢谢了

**Comment by kassadin** [comment]
贴出来recycler的创建过程

可能创建完recycler之后没有立即设置adapter吧

![qq20160120-0 2x](https://cloud.githubusercontent.com/assets/1104051/12439095/e675a234-bf67-11e5-9d3e-e056fee61625.png)

onCreate里初始化recycler之后线给个空的adapter试试

**Comment by wuchangfeng** [comment]
我大概知道我的错误在哪里了，第二张图，return stories 他的值是空的，因此没有值去绑定adapter。但是我还不知道怎么去解决他。更改如下图，验证我的猜想。但是这不是解决的办法，这样做会造成数据混乱。我想主要出现错误的原因还是我用的这个回调函数。希望有人能够指导一下。

在第二张图public void done(List<AVObject> list, AVException e) 函数执行结束后 mRecyclerViewAdapter.notifyDataSetChanged();

**Comment by kassadin** [comment]
图被你吃了。

**Comment by wuchangfeng** [comment]
![Uploading 2.jpg…]()

**Comment by WuXiaolong** [comment]
@kassadin 你这个方法是可行的，demo已经做了修改，多谢了。
mPullLoadMoreRecyclerView.setLinearLayout();
mRecyclerViewAdapter = new RecyclerViewAdapter(getActivity(), setList());
mPullLoadMoreRecyclerView.setAdapter(mRecyclerViewAdapter);
