### ISSUE TITLE
v1.04 瀑布流下 下拉刷新 异常 

### ISSUE THREAD

**Issue by LeronX** [WuXiaolong/PullLoadMoreRecyclerView#6]
瀑布流 拉取到下面 然后 返回上拉 只要第一行的item出现（即使只有一点点） 然后松手 也会执行onRefresh（） 并不是完全显示后才刷新

**Comment by SimonTse** [comment]
我也遇到了这个问题，但还没解决，不知道阁下解决了没有？

**Comment by WuXiaolong** [comment]
这个问题和加载更多是一样的，只要item一出现，就会触发下拉刷新或加载更多方法
