### ISSUE TITLE
你好,我是5.0的系统,上拉加载跟多不行是什么原因呀,属性都设置了

### ISSUE THREAD

**Issue by yuxingfafu** [WuXiaolong/PullLoadMoreRecyclerView#8]
mPullLoadMoreRecyclerView.setPushRefreshEnable(true);

mPullLoadMoreRecyclerView.setOnPullLoadMoreListener(new PullLoadMoreRecyclerView.PullLoadMoreListener() {
            @Override
            public void onRefresh() {

```
        }

        @Override
        public void onLoadMore() {               

        }
    });
```

**Comment by WuXiaolong** [comment]
数据要很多，占满屏幕，滑到底，才会触发上拉的方法
